_BASE_: GRES_Paper_Swin.yaml
MODEL:
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "MultiScaleMaskedLangReferringDecoder"
    RLA_LAYERS: [0, 2, 3, 4]
    GROUP_LAYERS: [2, 3, 4]
    GROUP_TOKENS: [15, 10, 5]
    GROUP_OUT_TOKENS: [15, 10, 5]
    GROUP_NHEADS: [4, 4, 4]
    GROUP_DEPTHS: [2, 2, 2]
    GROUP_DROP_PATH_RATE: 0.1
    GROUP_HARD_ASSIGN: True
    GROUP_GUMBEL: True