_BASE_: gres_swin_base.yaml
MODEL:
  MASK_FORMER:
    GROUP_LAYERS: [2, 5, 8]
    GROUP_TOKENS: [15, 10, 5]
    GROUP_OUT_TOKENS: [15, 10, 5]
    GROUP_NHEADS: [4, 4, 4]
    GROUP_DEPTHS: [2, 2, 2]
    GROUP_DROP_PATH_RATE: 0.1
