_BASE_: GRES_Repo_Swin.yaml
MODEL:
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "MultiScaleMaskedDualReferringDecoder"
    RLA_LAYERS: [0, 2, 5, 8]
    GROUP_LAYERS: [2, 5, 8]
    GROUP_TOKENS: [15, 10, 5]
    GROUP_OUT_TOKENS: [15, 10, 5]
    GROUP_NHEADS: [4, 4, 4]
    GROUP_DEPTHS: [2, 2, 2]
    GROUP_DROP_PATH_RATE: 0.1
    GROUP_HARD_ASSIGN: True
    GROUP_GUMBEL: True
    LANG_POS: True
    DEEP_SUPERVISION: True
    LANG_ATT_WEIGHT: 0.5
    NO_OBJECT_WEIGHT: 1.0
    MINIMAP_WEIGHT: 1.0
    MASK_WEIGHT: 1.0
    DICE_WEIGHT: 1.0
    ATTN_LOSS_WEIGHT: 0.2
    SIZE_DIVISIBILITY: 480
INPUT:
  IMAGE_SIZE: 480
  MIN_SCALE: 0.90
  MAX_SCALE: 1.0
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "refcoco"
